name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  validation:
    name: "Gradle wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      
  build:
    runs-on: ubuntu-latest
    needs: validation

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: get file with external properties
        run: echo "${{ secrets.EXTERNAL_PROPS_FILE }}" | base64 -d > apikeys.properties
 
      - name: display content of external props
        run: cat apikeys.properties
 
      - name: Make gradlew executable
        run: chmod +x ./gradlew
          
      - name: Build the app
        run: ./gradlew assembleDebug

      - name: Unit tests
        run: ./gradlew test
        
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/*
          
  unit-tests:
    runs-on: ubuntu-latest
    needs: validation

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: get file with external properties
        run: echo "${{ secrets.EXTERNAL_PROPS_FILE }}" | base64 -d > apikeys.properties
 
      - name: display content of external props
        run: cat apikeys.properties
 
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Unit tests
        run: ./gradlew test       

  instrumented-test:
    runs-on: macos-latest
    needs: validation
    timeout-minutes: 60
    strategy:
      matrix:
        api_level: [27]
        target: [default]

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: get file with external properties
        run: echo "${{ secrets.EXTERNAL_PROPS_FILE }}" | base64 -d > apikeys.properties
 
      - name: display content of external props
        run: cat apikeys.properties

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api_level }}
          target: ${{ matrix.target }}
          script: ./gradlew app:connectedDebugAndroidTest
